yarnPath: .yarn/releases/yarn-3.4.1.cjs
packageExtensions:
  '@toast-ui/editor@*':
    dependencies:
      prosemirror-transform: '*'
  '@toast-ui/react-editor@*':
    dependencies:
      prosemirror-transform: '*'
