export const products: string[] = ['Figma', 'Notion', 'Protopie', 'Framer'];
export const develops: string[] = [
  'JavaScript',
  'TypeScript',
  'React',
  'Vue',
  'Svelte',
  'Nextjs',
  'Java',
  'Spring',
  'Nodejs',
  'Go',
  'Express',
  'MySQL',
  'MongoDB',
  'Python',
  'Django',
  'php',
  'GraphQL',
  'Firebase',
  'Flutter',
  'Swift',
  'Kotlin',
  'ReactNative',
  'Unity',
  'Git',
  'C',
  'AWS',
  'Kubernetes',
];
export const designs: string[] = [
  'Figma',
  'Notion',
  'Protopie',
  'Framer',
  'Zeplin',
];
